// Links to images, assets, etc.
let links = {
    'index':            `${localPath}/index${html_extension}`,
    'our_team':         `${localPath}/our_team${html_extension}`,
    'our_mascot':       `${localPath}/our_mascot${html_extension}`,
    'join':             `${localPath}/join${html_extension}`,
    'openings':         `${localPath}/openings${html_extension}`,
    'sponsor':          `${localPath}/sponsor${html_extension}`,
    'rapid':            `${localPath}/projects/rapid${html_extension}`,
    'reach':            `${localPath}/projects/reach${html_extension}`,
    'overseer':         `${localPath}/projects/overseer${html_extension}`,
    'endeavour':        `${localPath}/projects/endeavour${html_extension}`,
    'forge':            `${localPath}/projects/forge${html_extension}`,
    'sandbox':          `${localPath}/projects/sandbox${html_extension}`,
    'calendar':         `${localPath}/resources/calendar${html_extension}`,
    'forms':            `${localPath}/resources/forms${html_extension}`,
    'articles':         `${localPath}/articles`,
    'admin':            `${localPath}/admin${html_extension}`,
    'videos':           `${localPath}/assets/images/videos`,
    'people':           `${localPath}/assets/images/people`,
    'pictures':         `${localPath}/assets/images/pictures`,
    'logos':            `${localPath}/assets/images/Logos`,
    'icons':            `${localPath}/assets/images/Icons`,
    'favicon':          `${localPath}/assets/images/favicon`,
    'css':              `${localPath}/css`,
    'js':               `${localPath}/js`,
    'models':           `${localPath}/assets/models`,
    'sponsor_logos':    `${localPath}/assets/images/SponsorLogos`,
    'sandbox_photos':   `${localPath}/assets/images/Sandbox`,
    'rapid_photos':     `${localPath}/assets/images/Rapid`,
    'reach_photos':     `${localPath}/assets/images/Reach`,
    'overseer_photos':  `${localPath}/assets/images/Overseer`,
    'endeavour_photos': `${localPath}/assets/images/Endeavour`,
    'missionWidget':    `${localPath}/js/missionWidget.js`,
};
